CC=g++

CFLAGS=-Wall
DEBUGFLAGS=-ggdb -g -gdwarf-2 -g3 #gdwarf-2 + g3 provides macro info to gdb

#
# Paths
#
SPACE_LIB = ../space-lib

INCPATH=-I./inc/ -I$(SPACE_LIB)/shakespeare/inc/ -I$(SPACE_LIB)/include
LIBPATH=-L./lib/ -L$(SPACE_LIB)/shakespeare/lib/
LIBS= -lshakespeare

buildBin:
	$(CC) $(CFLAGS) $(INCPATH) $(LIBPATH) $(DEBUGFLAGS) main.cpp -o bin/watch-puppy $(LIBS)

