CC=g++
CFLAGS=-Wall
DEBUGFLAGS=-ggdb -g -gdwarf-2 -g3 #gdwarf-2 + g3 provides macro info to gdb
INCPATH=-I./inc/
LIBPATH=-L./lib/ 

buildBin:
	$(CC) $(CFLAGS) $(INCPATH) $(LIBPATH) -DPC main.cpp -o bin/watch-puppy -lshakespeare
